[tool.black]
line-length = 99
exclude = '''(
    /home/runner/work/ixian/dist/*
  | /home/runner/work/ixian/.tox/*
  | /home/runner/work/ixian/.eggs/*
  | /home/runner/work/ixian/venv/*
  | snapshots/*
  )
'''
